// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_BoDLsNgA5s_S6H1CzL3of1gxQkWpKbY',
    appId: '1:898617185912:web:62d1aa2ccd734ab663ff8d',
    messagingSenderId: '898617185912',
    projectId: 'newsforum-e3174',
    authDomain: 'newsforum-e3174.firebaseapp.com',
    storageBucket: 'newsforum-e3174.appspot.com',
    measurementId: 'G-1KF35WWYYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_4lAYAUlluasLZhchOVgtFSeb-RtXqww',
    appId: '1:898617185912:android:9c38b319099308bd63ff8d',
    messagingSenderId: '898617185912',
    projectId: 'newsforum-e3174',
    storageBucket: 'newsforum-e3174.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYRRNZdpqCSGokGlds2kalMUvhbWKd9Xg',
    appId: '1:898617185912:ios:e9c04d07d3ee8e1263ff8d',
    messagingSenderId: '898617185912',
    projectId: 'newsforum-e3174',
    storageBucket: 'newsforum-e3174.appspot.com',
    iosBundleId: 'jd.news.forum.newsForum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYRRNZdpqCSGokGlds2kalMUvhbWKd9Xg',
    appId: '1:898617185912:ios:e8023a952860ce2763ff8d',
    messagingSenderId: '898617185912',
    projectId: 'newsforum-e3174',
    storageBucket: 'newsforum-e3174.appspot.com',
    iosBundleId: 'jd.news.forum.newsForum.RunnerTests',
  );
}
